[package]
name = "roblox/roact-rodux"
version = "0.5.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Roact = "roblox/roact@1.4.0"
Rodux = "roblox/rodux@4.0.0-rc.0"

